version: "3.8"
services:
  app:
    build: .
    ports:
      - "80:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/locatme
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
