name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull vishakh007/youlocateme:latest
      - name: Delete old Docker container
        run: sudo docker rm -f youlocateme-container || true
      - name: Create new Docker container
        run: sudo docker run -d -p 4000:4000 --name youlocateme-container vishakh007/youlocateme:latest
